services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: api-dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/app